const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { isPageRegistered } = require('./page-registration');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const app = JSON.parse(read('app.json'));
const menuJs = read('pages/menu/menu.js');
const menuWxml = read('pages/menu/menu.wxml');
const pageJs = read('package-order/order-confirm/order-confirm.js');
const pageWxml = read('package-order/order-confirm/order-confirm.wxml');
const pageWxss = read('package-order/order-confirm/order-confirm.wxss');
const sharedOptionsWxss = read('styles/spec-options.wxss');

assert.ok(isPageRegistered(app, 'package-order/order-confirm/order-confirm'));
assert.ok(menuJs.includes("wx.navigateTo({ url: '/package-order/order-confirm/order-confirm' })"));
assert.ok(menuWxml.includes('去确认'));
assert.ok(!menuWxml.includes('3D 开放确认'));
assert.ok(pageJs.includes('cartService.loadCart'));
assert.ok(pageJs.includes('catalogService.listDishes({ allowLocalFallback: false })'));
assert.ok(pageJs.includes('validateCartAgainstDishes'));
assert.ok(pageJs.includes('buildOrderDraft'));
assert.ok(!pageJs.includes('ORDER DRAFT READY'), 'order drafts are not logged in production');
assert.ok(pageJs.includes('catalogService.getCachedCatalog()'), 'confirmation renders the cart before the network check');
assert.ok(!pageJs.includes("wx.setStorageSync('orders'"));
assert.ok(!pageJs.includes("db.collection('orders')"));
assert.ok(pageJs.includes("require('../../services/orders')"));
assert.ok(pageJs.includes('orderService.createOrder(draft)'));
assert.ok(pageJs.includes('cartService.clearCart()'));
assert.ok(pageJs.includes('orderService.notifyOrderCreated(order.id)'));
assert.ok(!pageWxml.includes('mealTimeOptions'));
assert.ok(!pageWxml.includes('用餐时间'));
assert.ok(!pageJs.includes('mealTimeType'));
assert.ok(!pageJs.includes('requestedMealTime'));
assert.ok(pageWxml.includes('maxlength="{{maxOrderNoteLength}}"'));
assert.ok(pageWxml.includes('disabled="{{!canSubmit}}"'));
assert.ok(pageWxml.includes('提交点菜单'));
assert.ok(pageWxss.includes('env(safe-area-inset-bottom)'));
assert.ok(pageWxss.includes('position: fixed'));
assert.ok(pageWxss.includes('@import "../../styles/spec-options.wxss"'));
assert.ok(pageWxss.includes('grid-template-columns: 100rpx minmax(0, 1fr)'));
assert.ok(pageWxss.includes('writing-mode: horizontal-tb'));
assert.ok(pageWxml.includes('quantity-stepper'));
assert.ok(pageWxml.includes('quantity-circle'));
assert.ok(sharedOptionsWxss.includes('border-radius: 12rpx'));
assert.ok(sharedOptionsWxss.includes('min-height: 68rpx'));
assert.ok(sharedOptionsWxss.includes('border-radius: 50%'));
assert.ok(sharedOptionsWxss.includes('flex: 0 0 60rpx'));
assert.ok(pageWxss.includes('.item-bottom-row { width: 100%; min-width: 0;'));
assert.ok(pageWxss.includes('.quantity-control { width: auto; max-width: 100%; flex: 0 0 auto; margin-left: auto; }'));
assert.ok(pageJs.includes('pendingCartEdit'));
assert.ok(menuJs.includes('resumePendingCartEdit'));

console.log('order confirm integration tests passed');
