const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { isPageRegistered } = require('./page-registration');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const app = JSON.parse(read('app.json'));
const confirmJs = read('package-order/order-confirm/order-confirm.js');
const ordersJs = read('package-order/orders/orders.js');
const ordersWxml = read('package-order/orders/orders.wxml');
const detailJs = read('package-order/order-detail/order-detail.js');
const detailWxml = read('package-order/order-detail/order-detail.wxml');
const manageJs = read('package-admin/manage-orders/manage-orders.js');
const manageWxml = read('package-admin/manage-orders/manage-orders.wxml');
const familyApi = read('cloudfunctions/familyApi/index.js');
const notifyOrder = read('cloudfunctions/notifyOrder/index.js');

assert.ok(isPageRegistered(app, 'package-order/order-detail/order-detail'));
assert.ok(isPageRegistered(app, 'package-admin/manage-orders/manage-orders'));
assert.ok(confirmJs.includes('orderService.createOrder(draft)'));
assert.ok(confirmJs.includes('cartService.clearCart()'));
assert.ok(confirmJs.includes('if (result.idempotent !== true)'));
assert.ok(confirmJs.includes("wx.redirectTo({ url: `/package-order/order-detail/order-detail?id="));
assert.ok(ordersJs.includes('orderService.listMyOrders'));
assert.ok(ordersJs.includes('orderService.cancelMyOrder'));
assert.ok(ordersWxml.includes('还没有点菜单哦'));
assert.ok(ordersWxml.includes('本机旧订单'));
assert.ok(detailJs.includes('getMyOrderDetail'));
assert.ok(detailJs.includes('getManageOrderDetail'));
assert.ok(detailJs.includes('updateOrderStatus'));
assert.ok(detailWxml.includes('部分商品未标价'));
assert.ok(manageJs.includes('listManageOrders'));
assert.ok(manageWxml.includes('暂时没有订单'));
assert.ok(manageJs.includes("{ value: 'pending', label: '待确认' }"));
assert.ok(familyApi.includes('createOrder,'));
assert.ok(familyApi.includes('listMyOrders,'));
assert.ok(familyApi.includes('getMyOrderDetail,'));
assert.ok(familyApi.includes('cancelMyOrder,'));
assert.ok(familyApi.includes('listManageOrders,'));
assert.ok(familyApi.includes('getManageOrderDetail,'));
assert.ok(familyApi.includes('updateOrderStatus,'));
assert.ok(familyApi.includes('dishById[intentItem.dishId]'));
assert.ok(familyApi.includes('buildOrderItem(dish, intentItem)'));
assert.ok(!confirmJs.includes("db.collection('orders')"));
assert.ok(notifyOrder.includes("event.action === 'notifyNewOrder'"));
assert.ok(notifyOrder.includes('order.userOpenId !== openid'));
assert.ok(notifyOrder.includes("['admins', 'admin']"));
assert.ok(notifyOrder.includes('claimOrderNotification(db, orderDocumentId, openid)'));
assert.ok(notifyOrder.includes('markOrderNotificationSent(db, orderDocumentId)'));
assert.ok(notifyOrder.includes('resetOrderNotification(db, orderDocumentId'));

console.log('order cloud integration tests passed');
