const assert = require('assert');
const fs = require('fs');
const path = require('path');
const read = file => fs.readFileSync(path.join(__dirname, '..', file), 'utf8');
const theme = read('styles/theme.wxss');
const menu = read('pages/menu/menu.wxss');
const drink = read('components/drink-option-sheet/index.wxss');
const profile = read('pages/profile/profile.wxss');
const tab = read('components/custom-tab-bar/index.wxss');
['#A97A50', '#8B623E', '#F6F0E6', '#FFFCF7', '#E5D8C7', '#2B2119'].forEach(color => assert.ok(theme.includes(color)));
assert.ok(theme.includes('--wood-grain: repeating-linear-gradient'));
assert.ok(!theme.includes('url('), '木纹不加载图片资源');
[menu, drink, profile].forEach(css => assert.ok(css.includes('background-image: var(--wood-grain)')));
[menu, drink, profile, tab, read('app.wxss')].forEach(css => assert.ok(!/#(?:FF6347|E5533D|ef6a4c|d84c35|e45b3f)\b/i.test(css), '目标页面移除旧番茄色'));
assert.ok(menu.includes('width: 203rpx; height: 140rpx; flex: 0 0 203rpx'));
assert.strictEqual(203 / 140, 1.45);
assert.ok(menu.includes('font-size: 32rpx; line-height: 1.3; font-weight: 900'));
assert.ok(menu.includes('min-width: 0'));
assert.ok(menu.includes('-webkit-line-clamp: 2'));
assert.ok(drink.includes('.drink-sheet .spec-option-active'));
assert.ok(/\.drink-sheet \.spec-option-active\s*\{[^}]*color: #fff;/s.test(drink));
assert.ok(read('components/drink-option-sheet/index.wxml').includes('drink-sheet-layer brand-theme'));
assert.ok(drink.includes('env(safe-area-inset-bottom)'));
assert.ok(menu.includes('calc(320rpx + env(safe-area-inset-bottom))'));
const config = JSON.parse(read('app.json'));
assert.strictEqual(config.window.navigationBarBackgroundColor, '#F6F0E6');
assert.strictEqual(config.window.navigationBarTextStyle, 'black');
console.log('wood theme tests passed');
